library 'jenkins-shared@main'

pipeline {
    agent any
    stages {
        stage('build') {
            steps {
                echo 'building'
                sh 'echo qweasd'
                sharedTest()
            }
        }
    }
}
