jenkins:
  securityRealm:
    local:
      allowsSignup: false
      users:
        # create a user called admin
        - id: "admin"
          password: "admin"
  authorizationStrategy: loggedInUsersCanDoAnything

unclassified:
  location:
    adminAddress: "address not configured yet <nobody@nowhere>"
    url: "http://localhost:8080/"
  mailer:
    charset: "UTF-8"
    useSsl: false
  globalLibraries:
    libraries:
      - name: jenkins-shared
        retriever:
          modernSCM:
            scm:
              git:
                id: jenkins-shared
                remote: "ssh://git@git:22/git-server/repos/jenkins-shared"
                credentialsId: gitkey
                # traits:
                #   - cloneOptionTrait:
                #     extension:
                #       depth: 1
                #       noTags: true
                #       shallow: true
      # - name: "awesome-lib"
      #   retriever:
      #     modernSCM:
      #       scm:
      #         git:
      #           remote: "https://github.com/jenkins-infra/pipeline-library.git"

jobs:
  # - script: >
  #     job('example-1') {
  #         scm {
  #             git {
  #                 remote {
  #                     name('remoteB')
  #                     url('ssh://git@git:22/git-server/repos/jenkins-shared')
  #                     // url('git@git/jenkins-shared')
  #                 }
  #                 extensions {
  #                     // cleanAfterCheckout()
  #                     // relativeTargetDirectory('repo1')
  #                 }
  #             }
  #         }
  #     }
  # - script: >
  #     pipelineJob('example') {
  #         definition {
  #             cps {
  #                 script(readFileFromWorkspace('project-a-workflow.groovy'))
  #                 sandbox()
  #             }
  #         }
  #     }
  - script: >
      multibranchPipelineJob('main') {
          branchSources {
              git {
                  id('main-job-dude')
                  remote('ssh://git@git:22/git-server/repos/main')
                  credentialsId('gitkey')
                  includes('*')
              }
          }
          orphanedItemStrategy {
              discardOldItems {
                  numToKeep(20)
              }
          }
      }
  - script: >
      multibranchPipelineJob('templated') {
          branchSources {
              git {
                  id('templated-job-dude')
                  remote('ssh://git@git:22/git-server/repos/templated')
                  credentialsId('gitkey')
                  includes('*')
              }
          }
          orphanedItemStrategy {
              discardOldItems {
                  numToKeep(20)
              }
          }
      }
  - script: >
      multibranchPipelineJob('variant') {
          branchSources {
              git {
                  id('variant-job-dude')
                  remote('ssh://git@git:22/git-server/repos/variant')
                  credentialsId('gitkey')
                  includes('*')
              }
          }
          orphanedItemStrategy {
              discardOldItems {
                  numToKeep(20)
              }
          }
      }
  # - script: >
  #     job('bar') {
  #       steps {
  #         shell('echo Hello World!')
  #       }
  #     }
  # - script: >
  #     job('foo') {
  #       steps {
  #         shell('echo Hello foo!')
  #       }
  #     }
  # - script: >
  #     pipelineJob('pipeline-demo') {
  #       definition {
  #         cpsScm {
  #           scm {
  #             git {
  #               remote {
  #                 url('https://github.com/argeas/jcasc-example.git')
  #                 credentials('github-ssh-keys')
  #               }
  #               branches('master')
  #               scriptPath('Jenkins/Jenkinsfile.groovy')
  #             }
  #           }
  #         }
  #       }
  #     }

credentials:
  system:
    domainCredentials:
      - credentials:
          - basicSSHUserPrivateKey:
              scope: GLOBAL
              id: gitkey
              username: git
              passphrase: ""
              description: "SSH passphrase with private key file. Private key provided"
              privateKeySource:
                directEntry:
                  privateKey: "${readFile:/var/jenkins_home/gitkey}"
